# Generated by Django 3.2.7 on 2021-10-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentar', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentar',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tareas'),
        ),
    ]
