# Generated by Django 3.2.7 on 2021-10-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentar', '0003_comentar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentar',
            options={'verbose_name': 'comentar', 'verbose_name_plural': 'comentarios'},
        ),
    ]
