# Generated by Django 3.2.7 on 2021-09-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0003_auto_20210930_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='user',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
